### ISSUE TITLE
Refresh popup page onLoad

### ISSUE THREAD

**Issue by umarglobal** [rip747/popupwindow#2]
Hi is there a way to refresh the popup box before loading the contents ?

**Comment by rip747** [comment]
I'm not sure I understand your question. Can you give me san example of what
you want to do.
On Aug 12, 2011 10:58 AM, "umarglobal" <
reply@reply.github.com>
wrote:

**Comment by umarglobal** [comment]
Hi, Thanks for the quick response.

What im trying to do is load an embed into the popup window.. so my link looks like

`<a href="embed.php" class="popupwindow">Click here</a>`

The popup works fine and loads except in chrome. When i load it in chrome the popup is blank BUT on refreshing the popup the content loads fine. The embed.php has an embed flash script in there. Which is why i was asking if there is a way to refresh the popup before loading the content. That way it would work in chrome. 

Do you understand what i mean?

Thanks

**Comment by rip747** [comment]
What version of chrome and on what platform? Seems like this might be a bug
or simething. I'll have to look into this and get back to you.
On Aug 12, 2011 12:13 PM, "umarglobal" <
reply@reply.github.com>
wrote:

**Comment by umarglobal** [comment]
Im using Chrome 13.0.782.112 m, on Windows 7

For now ive added a php refresh code on the actual page that is being loaded into the popup window. 

Thanks
